# Generated by Django 3.2.4 on 2021-06-17 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_auto_20210617_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='text',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
